# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhSetup < Formula
  desc "A CLI tool that declaratively configures GitHub accounts, repositories, branch protection, teams, labels, CI, and governance from a YAML config file."
  homepage "https://github.com/amenophis1er/gh-setup"
  version "0.1.0"
  license "MIT"

  depends_on "gh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amenophis1er/gh-setup/releases/download/v0.1.0/gh-setup_darwin_amd64.tar.gz"
      sha256 "6efe958efca4f768e5ad69a15c53a20bc7b8a15214ecde74540ccad567b46883"

      define_method(:install) do
        bin.install "gh-setup"
        generate_completions_from_executable(bin/"gh-setup", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amenophis1er/gh-setup/releases/download/v0.1.0/gh-setup_darwin_arm64.tar.gz"
      sha256 "3f2c05fd70abbeeb9cb590b2be8942e9f4e24e403f19e6b535c4fbed8e618f51"

      define_method(:install) do
        bin.install "gh-setup"
        generate_completions_from_executable(bin/"gh-setup", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amenophis1er/gh-setup/releases/download/v0.1.0/gh-setup_linux_amd64.tar.gz"
      sha256 "af8f8ad3ff388f65f6e44681e9034c2572eacd70e6d4111a59f51855472cf331"
      define_method(:install) do
        bin.install "gh-setup"
        generate_completions_from_executable(bin/"gh-setup", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amenophis1er/gh-setup/releases/download/v0.1.0/gh-setup_linux_arm64.tar.gz"
      sha256 "63a453f0570c0a9d624df2e0ebf7694afa7e56fb0616fbf97ed771f552ba10c8"
      define_method(:install) do
        bin.install "gh-setup"
        generate_completions_from_executable(bin/"gh-setup", "completion")
      end
    end
  end
end
